### ISSUE TITLE
Can't verify...

### ISSUE THREAD

**Issue by tellustheguru** [thomascube/roundcube-plugin-kolab-2fa#16]
OS: Debian 11
Webserver: nginx
PHP Version: 8.0.28
Roundcube: 1.6.1

Log dump:

2023-03-01T11:46:05.012573+01:00 darke roundcube: <hl6iccau> RcubeUser::write() {"label":"Mobile App (TOTP)","created":xxxxxxxxxx,"secret":"XXXXXXXXXXXXXXXX"}
2023-03-01T11:46:28.211773+01:00 darke roundcube: PHP Warning:  Undefined array key "loglevel" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Storage/Base.php on line 85
2023-03-01T11:46:28.212459+01:00 darke roundcube: PHP Warning:  Undefined array key "loglevel" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Storage/Base.php on line 85
2023-03-01T11:46:28.212571+01:00 darke roundcube: PHP Warning:  Undefined array key "totp:096101dd5ac0aa97b67dae9d" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/kolab_2fa.php on line 317
2023-03-01T11:46:28.212662+01:00 darke roundcube: PHP Warning:  Undefined array key "storage" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 107
2023-03-01T11:46:28.212752+01:00 darke roundcube: <hl6iccau> RcubeUser::read() totp:xxxxxxxxxxxxxxxxxxxxxxxx
2023-03-01T11:46:28.212834+01:00 darke roundcube: PHP Fatal error:  Uncaught TypeError: hash_equals(): Argument #2 ($user_string) must be of type string, int given in /opt/www/roundcubemail-1.4.1/vendor/spomky-labs/otphp/lib/OTP.php:345
2023-03-01T11:46:28.212917+01:00 darke roundcube: Stack trace:
2023-03-01T11:46:28.212998+01:00 darke roundcube: #0 /opt/www/roundcubemail-1.4.1/vendor/spomky-labs/otphp/lib/OTP.php(345): hash_equals()
2023-03-01T11:46:28.213076+01:00 darke roundcube: #1 /opt/www/roundcubemail-1.4.1/vendor/spomky-labs/otphp/lib/TOTP.php(75): OTPHP\OTP->compareOTP()
2023-03-01T11:46:28.213152+01:00 darke roundcube: #2 /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/TOTP.php(85): OTPHP\TOTP->verify()
2023-03-01T11:46:28.213234+01:00 darke roundcube: #3 /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/kolab_2fa.php(634): Kolab2FA\Driver\TOTP->verify()
2023-03-01T11:46:28.213316+01:00 darke roundcube: #4 /opt/www/roundcubemail-1.4.1/program/lib/Roundcube/rcube_plugin_api.php(575): kolab_2fa->settings_save()
2023-03-01T11:46:28.213391+01:00 darke roundcube: #5 /opt/www/roundcubemail-1.4.1/program/include/rcmail.php(255): rcube_plugin_api->exec_action()
2023-03-01T11:46:28.213463+01:00 darke roundcube: #6 /opt/www/roundcubemail-1.4.1/index.php(278): rcmail->action_handler()
2023-03-01T11:46:28.213536+01:00 darke roundcube: #7 {main}
2023-03-01T11:46:28.213616+01:00 darke roundcube:   thrown in /opt/www/roundcubemail-1.4.1/vendor/spomky-labs/otphp/lib/OTP.php on line 345

**Comment by tellustheguru** [comment]
I reinstalles the plugin here is the log dump from this:

2023-03-01T14:14:19.536639+01:00 darke roundcube: PHP Warning:  Undefined array key "totp" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/kolab_2fa.php on line 301
2023-03-01T14:14:19.536837+01:00 darke roundcube: PHP Warning:  Undefined array key "storage" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 107
2023-03-01T14:14:19.536939+01:00 darke roundcube: PHP Warning:  Undefined array key "loglevel" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Storage/Base.php on line 85
2023-03-01T14:14:19.537012+01:00 darke roundcube: PHP Warning:  Undefined array key "loglevel" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Storage/Base.php on line 85
2023-03-01T14:14:19.537052+01:00 darke roundcube: PHP Warning:  Undefined array key "private" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 129
2023-03-01T14:14:19.537087+01:00 darke roundcube: PHP Warning:  Undefined array key "label" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 137
2023-03-01T14:14:19.537126+01:00 darke roundcube: PHP Warning:  Undefined array key "active" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 303
2023-03-01T14:14:19.537164+01:00 darke roundcube: PHP Warning:  Undefined array key "generator" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 209
2023-03-01T14:14:19.537203+01:00 darke roundcube: PHP Warning:  Undefined array key "private" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 129
2023-03-01T14:14:19.537269+01:00 darke roundcube: PHP Warning:  Undefined array key "hidden" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 136
2023-03-01T14:14:19.537352+01:00 darke roundcube: PHP Warning:  Undefined array key "label" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 303
2023-03-01T14:14:19.537434+01:00 darke roundcube: PHP Warning:  Undefined array key "label" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 311
2023-03-01T14:14:19.537532+01:00 darke roundcube: PHP Warning:  Undefined array key "private" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 129
2023-03-01T14:14:19.537617+01:00 darke roundcube: PHP Warning:  Undefined array key "created" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 303
2023-03-01T14:14:19.537696+01:00 darke roundcube: PHP Warning:  Undefined array key "created" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 311
2023-03-01T14:14:19.537737+01:00 darke roundcube: PHP Warning:  Undefined array key "secret" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 303
2023-03-01T14:14:19.537774+01:00 darke roundcube: PHP Warning:  Undefined array key "secret" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 303
2023-03-01T14:14:19.537808+01:00 darke roundcube: PHP Warning:  Undefined array key "secret" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 311
2023-03-01T14:14:19.537845+01:00 darke roundcube: <vnemhs6s> RcubeUser::write() {"label":"Mobile App (TOTP)","created":0000000000,"secret":"XXXXXXXXXXXXXXXX"}
2023-03-01T14:15:14.638697+01:00 darke roundcube: PHP Warning:  Undefined array key "loglevel" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Storage/Base.php on line 85
2023-03-01T14:15:14.682766+01:00 darke roundcube: PHP Warning:  Undefined array key "loglevel" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Storage/Base.php on line 85
2023-03-01T14:15:14.682874+01:00 darke roundcube: PHP Warning:  Undefined array key "totp:03dacbe3c8892879b7957aad" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/kolab_2fa.php on line 301
2023-03-01T14:15:14.682966+01:00 darke roundcube: PHP Warning:  Undefined array key "storage" in /opt/www/roundcubemail-1.4.1/plugins/kolab_2fa/lib/Kolab2FA/Driver/Base.php on line 107
2023-03-01T14:15:14.683072+01:00 darke roundcube: <vnemhs6s> RcubeUser::read() totp:xxxxxxxxxxxxxxxxxxxxxxxx

**Comment by tellustheguru** [comment]
I Solved the problem by installing version 3.5.5.2.
